# Generated by Django 5.2.3 on 2025-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('company_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('doc_number', models.CharField(blank=True, max_length=18, verbose_name='CPF ou CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Logradouro / Rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['company_name'],
            },
        ),
    ]
