# Generated by Django 5.2.3 on 2025-06-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_sale_production_order_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('A_VISTA', 'À Vista'), ('PARCELADO', 'Parcelado'), ('PIX', 'PIX'), ('CARTAO', 'Cartão de Crédito/Débito'), ('BOLETO', 'Boleto')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20, verbose_name='Status Financeiro')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_record', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Registro Financeiro',
                'verbose_name_plural': 'Registros Financeiros',
                'ordering': ['-created_at'],
            },
        ),
    ]
