# Generated by Django 5.2.3 on 2025-06-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='delivery_status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20, verbose_name='Status da Entrega'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_method',
            field=models.CharField(choices=[('NAO_DEFINIDO', 'Não Definido'), ('A_VISTA', 'À Vista'), ('PARCELADO', 'Parcelado'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto')], default='NAO_DEFINIDO', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
