# Generated by Django 5.2.3 on 2025-07-02 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialrecord_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADA', 'Atrasada')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments_list', to='finance.financialrecord', verbose_name='Registro Financeiro')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['financial_record', 'installment_number'],
                'unique_together': {('financial_record', 'installment_number')},
            },
        ),
    ]
