# Generated by Django 5.2.3 on 2025-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='installment',
            name='paid_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela'),
        ),
    ]
