# Generated by Django 5.2.3 on 2025-07-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_installment_paid_at_installment_paid_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
