# Generated by Django 5.2.3 on 2025-06-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionorder_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='checklist',
        ),
    ]
