# Generated by Django 5.2.3 on 2025-06-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_productionorder_checklist'),
        ('sales', '0002_sale_production_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='sales.sale', verbose_name='Venda de Origem'),
        ),
    ]
