# Generated by Django 5.2.3 on 2025-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_code_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
    ]
