# Generated by Django 5.2.3 on 2025-06-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='production_order_created',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
