# Generated by Django 5.2.3 on 2025-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cor_embalagem',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor da Embalagem'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cor_logo_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor do Logo 1'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cor_logo_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor do Logo 2'),
        ),
    ]
