# Generated by Django 5.2.3 on 2025-07-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitem_cor_embalagem_saleitem_cor_logo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='cor_logo_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor Logo 1'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cor_logo_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor Logo 2'),
        ),
    ]
