# Generated by Django 5.2.3 on 2025-07-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações da Venda'),
        ),
    ]
