# Generated by Django 5.2.3 on 2025-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='gramatura',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gramatura (g)'),
        ),
    ]
