# Generated by Django 5.2.3 on 2025-06-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('medida_x', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Medida X')),
                ('medida_y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Medida Y')),
                ('description', models.TextField(blank=True, verbose_name='Descrição (Marketing)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
