# Generated by Django 5.2.3 on 2025-07-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_quantity_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0, help_text='Quando o estoque atual atingir ou ficar abaixo deste valor, um alerta será gerado.', verbose_name='Estoque Mínimo'),
        ),
    ]
